input_unit: CHAR
lower_case: false
zero_digits: false
unit_freq: 20
label_freq: 40
vect_model: SKIPGRAM
window_size: 2
samp_thold: 0.001
embed_size: 16
embed_type: DENSE_AUTO
model_head: SOFTMAX
batch_size: 1024
num_epochs: 2
mixed_fp16: false
use_jit: true
train_optim: Adam
learn_rate: 0.001