input_unit: NGRAM
lower_case: true
zero_digits: true
unit_freq: 20
label_freq: 40
ngram_minn: 3
ngram_maxn: 5
ngram_self: ALWAYS
subword_comb: MEAN
vect_model: CBOW
window_size: 5
samp_thold: 0.001
embed_size: 256
embed_type: DENSE_CPU
model_head: SAMPLED
neg_samples: 5
batch_size: 1024
bucket_cbow: true
num_epochs: 5
mixed_fp16: false
use_jit: true
train_optim: Adam
learn_rate: 0.05