input_unit: WORD
lower_case: true
zero_digits: true
unit_freq: 20
label_freq: 40
vect_model: SKIPGRAM
window_size: 5
samp_thold: 0.001
embed_size: 256
embed_type: DENSE_CPU
model_head: NCE
neg_samples: 5
batch_size: 1024
num_epochs: 2
mixed_fp16: false
use_jit: true
train_optim: Adam
learn_rate: 0.05